### ISSUE TITLE
CONTRACT: Create NFT Forwarding Contract

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-nft#10]
### Issue To Be Solved
Some users may want to forward the NFTs that are sent to them to a different account's collection. Make a contract that defines a resource type that implements the `Receiver` interface from `NonFungibleToken` and deposits the NFT into another account. 

This is similar to the `TokenForwarding` contract from the flow-ft repo

### (Optional): Suggest A Solution
* Write the contract
* Test it with the `transfer_nft.cdc` transaction

**Comment by phouse512** [comment]
I know this is old but I'd like to take a stab at it if it's still relevant. @joshuahannan do you think this would still be helpful to have?

**Comment by joshuahannan** [comment]
@phouse512 we don't have a critical need for it, but it is always helpful to have more good smart contract examples of different use cases! It would be awesome if you could take a crack at it. I can help answer questions if needed! :)

**Comment by phouse512** [comment]
thanks @joshuahannan, I just published a PR for this - let me know if that's what you were thinking or if I missed what you were aiming for
