### ISSUE TITLE
Move testing to use Overflow

### ISSUE THREAD

**Issue by austinkline** [onflow/flow-nft#105]
### Issue to be solved

The tests in this repo aren't using either of the main testing libraries out there (overflow and flow-js-testing). Given that this repo's tests are in Go, I'd like to get tests moved to overflow.

https://github.com/bjartek/overflow

**Comment by joshuahannan** [comment]
I would like to get the tests moved to overflow also, but it hasn't really been a priority yet. Bjarte was kind enough to provide some examples for how it might work though, so we might be able to do it sometime soon.

**Comment by austinkline** [comment]
> I would like to get the tests moved to overflow also, but it hasn't really been a priority yet. Bjarte was kind enough to provide some examples for how it might work though, so we might be able to do it sometime soon.

Great to hear there's some interest internally about revamping the unit test frameworks being used! Any chance provided examples can be attached if they aren't on the overflow github in case I find the time to start moving things over?

**Comment by austinkline** [comment]
This might be it!
https://github.com/bjartek/flow-nft-overflow

**Comment by joshuahannan** [comment]
Yes, that is it. If you're interested in helping, you're welcome to make a PR. My only desire is that we keep all the non-cadence stuff in the `lib/` directory if possible. If nobody else gets to it soon, I'll probably try to work on it in a few weeks

**Comment by joshuahannan** [comment]
We decided to use flow-js-testing for this [in this PR](https://github.com/onflow/flow-nft/pull/116), so we won't be using overflow in this repo for now. I'll look into using it in other repos though
