### ISSUE TITLE
Make the concept of core views clear at the docs

### ISSUE THREAD

**Issue by alilloig** [onflow/flow-nft#113]
### Issue To Be Solved
Since the concept of core views is used by the [NFT catalog](https://nft-catalog.vercel.app/) it should be crystal clear on the README and even in the NFTView comments which views are considered the core views, and maybe even a reference about the need of implementing NFTView to be displayed on the NFT catalog

**Comment by alilloig** [comment]
@satyamakgec @albeethekid referencing the NFT catalog on the documentation (this repo README.md), yay or nay?

**Comment by albeethekid** [comment]
> @satyamakgec @albeethekid referencing the NFT catalog on the documentation (this repo README.md), yay or nay?

Can't hurt

**Comment by satyamakgec** [comment]
> @satyamakgec @albeethekid referencing the NFT catalog on the documentation (this repo README.md), yay or nay?

Yeah it is perfectly fine
