### ISSUE TITLE
Reformat NonFungibleToken Go tests in JavaScript

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-nft#120]
### Issue To Be Solved
In keeping with the tests to be written for NFTForwarding contract (See issue https://github.com/onflow/flow-nft/issues/10 and PR https://github.com/onflow/flow-nft/pull/116), tests for the NonFungibleToken contract should be written in JavaScript, leveraging `flow-js-testing`.

**Comment by austinkline** [comment]
fyi there has also been discussion about moving this repo to use overflow:
https://github.com/onflow/flow-nft/issues/105

And there is already some example usage for how to make that happen from @bjartek 
https://github.com/bjartek/flow-nft-overflow

**Comment by joshuahannan** [comment]
https://github.com/onflow/flow-nft/pull/116 Addresses this, so we can close this when that gets merged

**Comment by sisyphusSmiling** [comment]
Closed by PR#121
