### ISSUE TITLE
Developer Portal broken link

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-nft#137]
![2022-11-15 14 02 20](https://user-images.githubusercontent.com/3970376/202014606-20d6e845-4b7b-4c54-a363-11894f5868ba.gif)

### Problem

developer portal link is broken. There needs to be a 

### Steps to Reproduce 

see gif above

Need to create a redirect to overview if user clicks on `flow NFT` nav

**Comment by joshuahannan** [comment]
Any help you need here @bthaile or do you have a handle on it?

**Comment by bthaile** [comment]
this has been fixed, closing
