### ISSUE TITLE
Normalize flow.json

### ISSUE THREAD

**Issue by alilloig** [onflow/flow-nft#139]
### Issue To Be Solved
New contracts added to this repository need to be reflected on the flow.json file in order to allow smooth local deployments for developers using `flow run`

**Comment by joshuahannan** [comment]
Looks good to me at a first glance! Have you tested it yet?

**Comment by alilloig** [comment]
Yep, it deploys everything smoothly

<img width="1278" alt="Screenshot 2022-11-21 at 16 51 48" src="https://user-images.githubusercontent.com/6607145/203099074-625f964b-ed08-4c35-80c7-d138082c386b.png">
