### ISSUE TITLE
Adequate comments to docgen tool and include generated docs in repo

### ISSUE THREAD

**Issue by alilloig** [onflow/flow-nft#140]
### Issue To Be Solved
We need to go through all the comments on the repo contracts, double check that they fit the docgen format, generate the doc and include in the repos

**Comment by alilloig** [comment]
@joshuahannan updating the docs on the ft repo, I just realised that we don't have docgen tool comments on the ExampleNFT (I generated those for the ExampleToken). Do you think that would be something worth to include?

**Comment by joshuahannan** [comment]
Didn't you already include them in the default implementations PR?

**Comment by alilloig** [comment]
Not for ExampleNFT, will do since you don't seem against it, that PR isn't merged yet and I finally did the same for the ExampleToken
