### ISSUE TITLE
Create an example of an NFT burner

### ISSUE THREAD

**Issue by alilloig** [onflow/flow-nft#141]
### Issue To Be Solved
`ExampleNFT` does not include a Burner resource, which will make a nice example for how to burn NFTs (in a similar manner as we showcase that on `ExampleToken`

### Suggest A Solution
· Include an `NFTBurner` resource on the ExampleNFT contract
· Update docs
· Create tests for the new feature

### Context
This concern was raised by a community member on our discord server https://discord.com/channels/613813861610684416/717035372248432660/1047055831499284500

**Comment by joshuahannan** [comment]
What kind of functionality would you be looking for besides just destroying? We can already call `destroy` on any resource, so we didn't originally include a burner since it seemed kind of unnecessary.

**Comment by bjartek** [comment]
Emitting an event on burning would make total sense to me. Yes you can emit an Withdraw event from the transaction but you really do not know what happend with it if you do not emit an event. It could be escrowed somewhere or something.

**Comment by bluesign** [comment]
I think better option is to somehow `destroy` to emit an event. But unfortunately this is also not solution because of how vault is designed. 

Here problem is `Burner` is not a concept for NFT. You can just destroy the NFT as @joshuahannan said.

**Comment by joshuahannan** [comment]
Yeah, we'd have to have some way to enforce that every implementation emits a destroy event in their destroy block of `NFT`, which isn't possible. We could have cadence emit a built in event every time a resource is destroyed, which might be useful. Would that help? Is there an issue open for it already?

**Comment by alilloig** [comment]
I agree that the Burner isn't needed, and I'm also quite onboard for emitting an event on `destroy` on ExampleNFT for showing people how to keep track of burned NFTs, but I'm not sure about enforcing an event for every single resource that gets destroyed. Two reasons, first, won't that mean a lot of extra load to the network? second, won't be legitimate for a developer for not wanting their resource to "communicate" to the world that they got destroyed?

Anyway I'm closing this issue, probably we can move this discussion to the cadence repo
