### ISSUE TITLE
MetadataViews.getXXX functions does not work with INFT

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-nft#145]
All the getXXX functions in MetadataViews currently require that you send in a &{Resolver}, NFT does not implment MetadataViews.Resolver. 

I see two options here:

- duplicate methods that also take an &{INFT}
- for nftv2 ensure that NFT resources also implement MetadataViews.Resolver (they will have to be updated regardless and it is a very easy fix)

**Comment by joshuahannan** [comment]
We're definitely going to do your second bullet point for nft v2. Do you think it is urgent to create the duplicate methods in the meantime for the current standard or not necessary?

**Comment by bjartek** [comment]
That depends on how far it is off really.
