### ISSUE TITLE
Add a view to capture constraints that IP rights holders may require consumers of their IP to observe

### ISSUE THREAD

**Issue by satyamakgec** [onflow/flow-nft#150]
### Issue To Be Solved
IP rights holders of certain NFT collections may wish to signal restrictions or constraints to the usage of their restricted content, as well as indicating marketplaces which they have approved their NFTs for sale in. 

### Suggest A Solution
Agree a view standard which enables IP right holders to specify the relevant constraints, such as which marketplaces, terms and conditions of use or other IP related aspects which can reside with a NFT

**Comment by aishairzay** [comment]
If the driving worry is that royalties wont be enforced by a marketplace, what is going to encourage (or force) a marketplace that wouldn't have respected the royalties view to respect the allowed marketplaces view?

**Comment by bluesign** [comment]
this is not a good idea, I think it should be up to the user to decide which marketplace to use.

**Comment by franklywatson** [comment]
@aishairzay we're not going to tackle royalties here as part of this, somehow that got confused with this IP rights view. We're proposing that change in another PR, where rather than having individual transactions wire up the RoyaltyView to saleCut, we would do this during Listing init() so it's always done when a listing is created.

**Comment by franklywatson** [comment]
@bluesign yes it goes against the spirit of open marketplaces but in the end major brands and other IP rights holders always impose constraints, whether that is the right to play back the moment video on ones own site, or otherwise where they approve os a sale happening. It's better to have a construct to support this rather than have Dapper Wallet or other places enforcing rules of some kind

**Comment by bluesign** [comment]
@franklywatson I hard disagree on this; for few reasons: 

- the standard is not a place to make few IP right holders happy, putting it in standard encourages others to do the same, marketplaces then encourage dapps with extra royalty for exclusivity
- storefront's selling point was user will list, marketplaces will compete to show (faster, better UX, lower commission)
- competition already brought us lower marketplace fees (flowty)
- I think in the end users lose, as ownership loses value
 
I think if the dapper wallet does not enforce illogical restrictions like this, they can try to convince IP owners. This is a restriction non existing in other chains.

**Comment by franklywatson** [comment]
@bluesign you make valid points, but nothing you have mentioned solves the problems that IP holders face. It's simply a reality that we have to contend with. Are you saying that those who are sensitive to their IP rights should not use Flow or the Storefront?

**Comment by bluesign** [comment]
@franklywatson We have discussed similar things before ( like: https://github.com/onflow/flow-nft/issues/106 ). It didn't move much, but it is a better solution for this problem. They can put what they want to grant and what they want to restrict in their licenses. 

I feel putting it into metadata views in a structured way will later be abused or created an exception to respect that metadata view; it may even create legal responsibility for marketplaces to watch them ( as we are putting into the standard )
 
Also, there will be marketplaces that respect royalties, or IP holders' requests, but some that do not. 

PS: Btw putting some view like this out of the standard ( dapper wallet can maintain, for example ) is.a possibility too. I feel we need to be little neutral as 'flow'

**Comment by franklywatson** [comment]
Thanks for sharing, i remember that whole thread wasn't sure where it had ended up. I like the suggestion to make the view outside the standard, but there's a problem. If my IP restricted project is minted as a standard NFT, then that is a defacto statement of openness because the NFT conforms to the standard. The rest of the ecosystem can see the NFTs and so other contracts can/will/should be able to freely interact/transact, providing it's the account owner requesting it. 

That's what makes a Dapper Wallet maintained set of rules a problem. The NFTs all still live in an account. If DW has to enforce something using a custom view outside the standard, how can they ensure that othesr will too - and as soon as we start asking ourselves how can we enforce for everyone, we're talking a standard again. You see my point?

**Comment by bluesign** [comment]
@franklywatson main problem I see, let me try to rephrase it. 

- How many NFT projects we have? How many of them need this view? 

if it is > 50-60 percent, put to standard. ( like royalty, display, nftview, maybe even license ). If it is 40, but solving a very big problem, I would not oppose. Problem is for allowed marketplaces view there is no such need, I agree maybe few brands, IP owners need. Maybe you can share with us some projects want this? Maybe demand is much higher than we guess. But I don’t think it can satisfy the requirement to be in the standard. 

This like this: we didn’t put any basketball specific stuff to standard, although number of basketball related nfts I am sure is more than number of projects that needs market restriction view. 

> If DW has to enforce something using a custom view outside the standard, how can they ensure that other will too 

there is no guarantee that even this is in standard it will be respected. Nftstorefront is standard, there are a lot of marketplaces don’t use it. Dapper Wallet like rest of the wallets, or dapper marketplace like rest of the marketplaces; do what is the sane thing to do; will put the view out, if people adopt, they will adopt.

**Comment by bjartek** [comment]
How is this going to be enforced?

Anybody can create a marketplace contract and chose to ignore this?

**Comment by satyamakgec** [comment]
> How is this going to be enforced?
> 
> Anybody can create a marketplace contract and chose to ignore this?

There is a way to enforce this, If we check whether NFT implements the IPRights view and it has a list of marketplaces then the contract can match whether the provided `commissionReceivers` is a subset of the marketplaces list then move forward with the listing otherwise fail the `createListing()` transaction.

**Comment by satyamakgec** [comment]
> @satyamakgec thanks, it was obvious it is some innocent metadata view, and some enforcement action will come after.
> 
> Maybe later we put mag.sender to cadence, only signed by markerplace / IP owner transactions can move NFT. /s

I understand where you are coming from, We deeply value our community feedback and we want to collect more feedback before concluding anything. So stay tuned 😃

**Comment by cybercent** [comment]
Just a reminded that this are metadata **views** - the scope is to read data, not enforce/limit usage of the NFT.
Marketplaces and main drop sites can use tools like Chainalysis to stay compliant/filter IPs.

**Comment by joshuahannan** [comment]
We already have a proposal open for something similar to this: https://github.com/onflow/flow-nft/issues/106

**Comment by satyamakgec** [comment]
@joshuahannan but does it cover the list of marketplaces where IP holder list would be provided ? #106 is only about licensing details and maybe I don't know how licensing issue works but can you fill in how does the #106 solve the listed problem.

**Comment by bluesign** [comment]
@satyamakgec it covers right management totally, unless you have some plan to support enforcement of this on chain with ‘standard’ contracts. 

i tried to hint on my previous sarcastic message but seems either message is not going to the other side, or you guys are really don’t care.

if dapper wallet or IPs want this, they can come here and discuss. Please stop being soldiers for them and die for this stupid cause. Little ethics never killed nobody. 

Can we just please just close this issue already.

**Comment by bjartek** [comment]
> > How is this going to be enforced?
> > Anybody can create a marketplace contract and chose to ignore this?
> 
> There is a way to enforce this, If we check whether NFT implements the IPRights view and it has a list of marketplaces then the contract can match whether the provided `commissionReceivers` is a subset of the marketplaces list then move forward with the listing otherwise fail the `createListing()` transaction.

But you do not control all the contracts? This is not sustainable.

**Comment by joshuahannan** [comment]
I think this discussion should probably be merged with #106. The rights described in here can be shown in that view and that view is more fleshed out andconfigurable. Also, we're creating these issues for discussion, so if you disagree, please be polite in your disagreement. I'm going to close this issue so we can have more discussion there
