### ISSUE TITLE
Extended Edtition view

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-nft#154]
In the doodles project we have a contstruct that I think is interesting enough that I propose that it should be expressed as a seperate View in the standard. 

(I am not even sure if edition is the right word to use here)
ExtendedEditions: a struct that is Edtionable and Retireable.
- name: the edition have a name, for doodles this could be "Core" or "Unique"
- type: the type of this edition, this can be that it is a "set" or a "position" or a "template" or a "season"
- number: the number this item has in the edition
- status: is this edition still open for minting or is it closed
- maxNumber: a number signaling either final edition count or circulating supply if still active
- traits: Additional traits/tags/attributes that this edition may have. 

A concrete example
 - Wearables in doodles are in a `set`
 - each set has a given name and a counter to keep track of how many have been minted with that set
 - a set also has a creator

We tried modelling this as an Edition view and aditional Traits but that was confusing was the feedback I got so right now that data has been removed from the Views that wearables expose. 

### Contributors

We need more feedback on if this is something that should be represented by a standard view. If you want to see this as a view, please respond!

**Comment by joshuahannan** [comment]
Is this related to #152 ? I'm sorry, but I don't fully understand the need for this either

**Comment by bjartek** [comment]
In doodles i tried to expose the rich data model we have as a combination of traits and editions but got pushback from gaia and flowty that it was confusing. Thus the need for a richer view to expose the data.

**Comment by bjartek** [comment]
If this is of no interest to the rest of the flow community we can always just expose it as a doodles specific view in our own Views file.

**Comment by joshuahannan** [comment]
yeah, I think we would need to see other examples and needs to know if we need to make this a standard view or not, but I'm leaning towards no, but I'm happy to support it if a bunch of others think it is a good idea and we get some other examples

**Comment by joshuahannan** [comment]
@bjartek Are you okay with me closing this or do you want to get some more opinions on it first?

**Comment by bjartek** [comment]
Feel free to close
