### ISSUE TITLE
Impossible to count number of NFTs in large collections and get the IDs

### ISSUE THREAD

**Issue by cybercent** [onflow/flow-nft#184]
### Issue to be solved

`getIDs().length` breaks when used on accounts with large NFT collections like `0x329feb3ab062d289.661249`

```
failed to retrieve slab 0x329feb3ab062d289.661249: get value failed: [Error Code: 1110] computation exceeds limit (100000)
```

### Suggested Solution

- Add way to get the count of total NFTs by avoiding `getIDs().length`
- Add way to get a slice of the IDs in the collection.

@joshuahannan I'm tagging you here as this might be interesting for the V2 standard.

**Comment by austinkline** [comment]
Can this be done with what we have currently? I'd guess we might have to tackle it with the V2 standards coming out with stable cadence. The main issue as I understand it is that `getIDs` has to load all IDs into memory which is just too costly for large collections

**Comment by turbolent** [comment]
To allow users to query the size of the collection, `Collection` should provide a getter function for it, so that users do not need to rely on the inefficient `getIDs().length`.

This is simple by adding:
```cadence
fun getCount(): Int
    return ownedNFTs.length
}
```

**Comment by cybercent** [comment]
Looks good for getting ID count, any idea on getting a slice of the IDs without loading all of them with getIDs ?

**Comment by joshuahannan** [comment]
Yeah, I think getting a slice like that will require an update to Cadence

**Comment by bjartek** [comment]
You could do iteration over the map and fetch the first x ones?

**Comment by joshuahannan** [comment]
`getLength` addresses this so I am closing
