### ISSUE TITLE
NFTMinted event?

### ISSUE THREAD

**Issue by rheaplex** [onflow/flow-nft#34]
### Issue To Be Solved

The NFT standard does not have an event to indicate that a token has been minted.

Rather we must infer that a token has been created by watching for an initial `Deposit` event to a Collection.

If the NFT is not saved to a collection, its creation may not be visible from events.

### (Optional): Suggest A Solution

Add the following event to the NFT standard contract:

```
pub event Minted(id: UInt64, by: Address?)
```

Listening for this event would allow off-chain code to establish when to start listening for further events regarding the NFT with that ID.

### (Optional): Context

This is not a blocker, and may not be a desirable enhancement:

* Batch minting of tokens may be better represented by a single bulk event.
* There may be more useful information that a contract wishes to contain in a token creation event. Requiring a standardized event means that the contract must emit a second, nonstandard, event at increased cost of gas and block event space.
* A contract may not wish to advertise minting or to use that terminology.

**Comment by briandilley** [comment]
Isn't there already `NFTCreated` and `NFTDestroyed` ?
