### ISSUE TITLE
Collection Index Capability

### ISSUE THREAD

**Issue by rheaplex** [onflow/flow-nft#36]
> It would be very nice if it was possible to get a capability to an index in a Collection though. That would actually be HUGE.

In the KittyItems code we store an NFT.Provider and a tokenID (more general purpose code would store a uuid, or an id and a Type) then attempt to fetch that.

Wrapping this up as a capability that any collection can vend would be very interesting.

**Comment by joshuahannan** [comment]
Closing this issue since this is listed in #48
