### ISSUE TITLE
Looking to verify ownership of Moments

### ISSUE THREAD

**Issue by free-soellingeraj** [onflow/flow-nft#37]
### Issue To Be Solved
I am looking for a way to verify the ownership of a moment.  The ability to link to the identity of the owner of the Moment.

### (Optional): Suggest A Solution
Preferrably using the hash of the moment mp4 file, or another of the artifacts linked to the NFT.

Even still, just tell me what I need to know in order to verify the ownership of the Moment.

**Comment by robmyers** [comment]
Heya. This is a https://github.com/dapperlabs/nba-smart-contracts/ question but I'll answer it here. 😺 

For onchain verification see:

https://github.com/dapperlabs/nba-smart-contracts/blob/master/contracts/TopShot.cdc

TopShot.Play.metadata contains media file information.

Topshot.playDatas maps playIDs to Plays.

NFT.data.playID refers to a playID. This can be used to look up the Play, access its metadata, and associate that with the NFT's Resource.owner address.

You can query this in a Cadence script via a Flow access node. See here:

https://github.com/dapperlabs/nba-smart-contracts/tree/master/transactions/scripts

If this is the wrong level of abstraction let me know. 😺
