### ISSUE TITLE
in read_nft_id.cdc  . can't get metadata

### ISSUE THREAD

**Issue by magic373** [onflow/flow-nft#50]
in read_nft_id.cdc  
how to get metadata, only get NTF id

**Comment by MaxStalker** [comment]
> in read_nft_id.cdc how to get metadata, only get NTF id

Currently standart doesn't require `metadata` field to be implemented, only `id` field is required:
https://github.com/onflow/flow-nft/blob/master/contracts/NonFungibleToken.cdc#L78-L80

So there is no single way to get it. Contracts can (and do) implement their own way of storing and providing metadata.
There are open discussion about new metadata standart, which you can find here:
https://github.com/onflow/flow-nft/issues/9
