### ISSUE TITLE
Identity View

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-nft#56]
## Instructions

Add a Identity view so that resources can Identify who they are

### Problem

How do you know that you are buying a flowverse sock from the correct minter? Discovering this progrematically is very hard and almost impossible. 

Also the very useful uuid field is hidden from the NFT.

### Acceptance Criteria

Implement a View in the new NFT standard that expose some common information about an NFT, most of this can be default implemented in the contract, atleast there could be a method to generate it for you. 

The information I can think of is:

- id: AnyStruct, the id of this resource, the reson this is anyStruct is because the view is not tied to NFT and other resources can have other ids. (like .find names are identified by the name)
- type: Type, the Type of this resource
- uuid: the UIn64 uuid field
- discriminator: This is a text field to discriminate NFTS that are of the same Type but different origin
  
Adding this view to the Standard will and getting it adopted will make it easer for everybody to uniqely identify resources. The reson id/type is there is really to be able to map from the old pattern to the new pattern.

**Comment by bjartek** [comment]
Come to think of it, a lot of the information here is already accessible runtime from a &{MetadataViews.Resolver} reference like id, type and uuid. So maybe this could just boil down to a `Minter`or  `Source` view that discriminates who really minted this, if the contract supports multiple minters.

**Comment by bjartek** [comment]
Come to think of this even more, I do not belive id is present in `&{MetadatViews.Resolver}` so i still think this is a good idea.

**Comment by hichana** [comment]
@bjartek this is an interesting nut to crack here. How do other chains solve this problem if at all? Or if there is no technical solution a given other chain, how does the community have some consensus on the correct minter?

**Comment by bjartek** [comment]
Well on chains that are not resource oriented a shared contract would give bad resource isolatiob, but on flow resources are owned by users not contracts. So i guess the problem is not there.

**Comment by hichana** [comment]
I was thinking like on an evm chain if someone were to clone and deploy a contract, who is to say which one is the 'correct minter'? Maybe that's what the 'discriminator' field here would do?

**Comment by joshuahannan** [comment]
@bjartek Can you elaborate a bit more on the discriminator? I'm not sure how that is used to differentiate?

Also, what is stopping someone from faking the discriminator and the nonce?

for `path`, you're saying that if you had a random generic NFT, you could get the path from it to deposit it without knowing the actual contract it came from?

**Comment by bjartek** [comment]
Discriminator could be used to discriminate things like

 - the minter of a starly card
 - the kind of nft in gaia
 - the kind of nft in mintstore
 - the minter in rarible

Basically all shared contracts that can be grouped on something besides where they happend to be stored.

**Comment by bjartek** [comment]
Nobody is stopping anybody from faking anything no matter the view. I do not see what makes it relevant.

**Comment by bjartek** [comment]
If you know the path you can _try_ to borrow the NFT.Receiver or NFT.CP on that path (not everybody kink them :( )
and deposit the item to somebody else. In things like alchemy and find this is now hard coded everywhere.
