### ISSUE TITLE
Add getDefaultStoragePath() functions to FT+NFT interfaces

### ISSUE THREAD

**Issue by justjoolz** [onflow/flow-nft#57]
### Issue To Be Solved

Currently using (arbitrarily) named value fields is the suggested best practice to obtain the default storage paths used by a contracts a Vaults/Collections etc.

https://docs.onflow.org/cadence/anti-patterns/#named-value-fields-are-preferable

### (Optional): Suggest A Solution

Suggest adding a function that returns this path as part of the interface:

`
getDefaultStoragePath() : StoragePath?
`

Same could be done for Public and Private paths. This would save referencing the original contracts individually and would allow these default paths to be obtained programatically. 

Or could this plausibly be incorporated as part of the metadata standard?

**Comment by bluesign** [comment]
I think another option can be to query storage with resource type.  Normally I don't think anyone cares which path the resource is stored ( also can be non-default path in case of advanced user ) 


PS: I really wish to get rid of paths totally ( at least in the user experience ).  For me transaction scripts currently are super bloated.

**Comment by joshuahannan** [comment]
I agree that this would be great to have. I've added it to the https://github.com/onflow/flow-nft/issues/48 issue so it is included in the upcoming discussions for improvements to the standards. I'm going to close this issue since it is mentioned there
