### ISSUE TITLE
Consistent ability to pull Set information for a NFT (Set View)

### ISSUE THREAD

**Issue by SeanRobb** [onflow/flow-nft#66]
### Issue To Be Solved
The ability for NFT's to have sub-categories or groupings that are exposed in a consistent way.

### Solution 1: MetadataViews.SetView
Introduce the MetadataViews.SetView view:

// ... MetadataViews Contract ...

pub struct SetView {
  pub let id: UInt64
  pub let name: String?
  pub let description: String?
}

This `id`, `name`, and `description` would be for the set information instead of the individual NFT. `name` and `description` are optional as `id` is the only needed field to differentiate a `Set` within an NFT. This route makes determining the NFT set information easy for a single NFT but is not great for having a good on-chain index of all the NFT's within a set.
  
### Context
Ideally, this could be implemented in a way so that someone could offer or buy anything within a set then any NFT within that set could fulfill the request.

For example, if I want any NFT from the Ballerz set from [Gaia](https://flowscan.org/contract/A.8b148183c28ff88f.Gaia/overview) or any [NBA Top Shot](https://flowscan.org/contract/A.0b2a3299cc857e29.TopShot/overview) from a certain Set or Play it would be nice to allow for a Metadata View so that NFT creators can group these logically allowing for Sales and Offers to potentially be grouped as well.

**Comment by joshuahannan** [comment]
Are you suggesting it be called `SerialNumber` or `SetView`. I see both in your proposal.

I feel like this information can already be communicated in the regular `Display` view, that we are doing with Top Shot already: https://github.com/dapperlabs/nba-smart-contracts/blob/master/contracts/TopShot.cdc#L596-L606

What is the benefit of having an additional view for this?

**Comment by SeanRobb** [comment]
@joshuahannan Thank you for pointing this out. Updated to SetView. 

This view would not be explicitly used only for displaying the data. This could additionally be used for filtering or offers for sets. In the Topshot example, the SetView data would be. 

`
// ... TopShot Contract ...
          MetadataViews.SetView(
              id: self.data.playID,
              name: self.name(),
          )
`

In the Ballerz case it is a set of the Gaia NFT
`
// ... Gaia Contract ...

    // getSetDescription returns the name that the specified Set
    //            is associated with.
    // 
    // Parameters: setID: The id of the Set that is being searched
    //
    // Returns: The name of the Set
    pub fun getSetDescription(setID: UInt64): String? {
        // Don't force a revert if the setID is invalid
        return Gaia.setDatas[setID]?.description
    }


          MetadataViews.SetView(
              id: self.data.setID,
              name: Gaia.getSetName(self.data.setID),
              description: Gaia.getSetDescription(self.data.setID),
          )
`

`Set` seems to have different contexts in each contract so I am open to different terminology. The biggest benefit of this View is to allow for dApps or smart contracts to be able to recognize like NFTs. In the NBA Top Shot case a user would want to know if [this Kevin Durant jump shot](https://nbatopshot.com/listings/p2p/e7b9646c-9997-46c8-909f-2a2b67389023+af8a4c1f-12d3-429d-9e2c-e8d8d7a6c5b9) is the same as this [Kevin Durant jump shot](https://nbatopshot.com/listings/p2p/6783b9d8-44c5-49c7-87e0-be217af963e9+0a06ada6-2c9c-4479-9c93-b1485e89261a). In the Gaia use case would want to know if this [Gaia NFT](https://ongaia.com/ballerz/2775) is the same as [this Gaia NFT](https://ongaia.com/shareef/15215). Ideally, we can set a standard to group these like assets that are controlled by the NFT Contract maintainer. Exposing this ID in a consistent way will allow for a Smart Contract to easily differentiate this where the name and description can allow for dApps to display this information nicely.

**Comment by joshuahannan** [comment]
Closing this issue in favor of a more focused issue on general NFT metadata
