### ISSUE TITLE
DOCS: Document Metadata + Royalties Standard

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-nft#72]
### Issue To Be Solved
We've finished the royalties standard. Now we need docs for how to use it and integrate with it.

### Suggest A Solution

Discussion here: https://www.notion.so/dapperlabs/Summary-of-Royalty-view-discussion-d177fa4d5a134127965dd3f09118981e

- [x] Update the README in flow-nft to mention and describe royalties and link to the new docs about them

**Comment by joshuahannan** [comment]
@tyllenb

**Comment by tyllenb** [comment]
@joshuahannan Yeah I agree. I've already had developers start integrating it and they are having no issues with the royalty standard. If any additional docs are needed I'll talk to the devs and see where they are having issues and then build it out for them. Looks good to me though!

**Comment by joshuahannan** [comment]
ok. Make sure you are letting them know to use the new token receivers as described in the docs instead of their default receivers

**Comment by tyllenb** [comment]
Will do, so they would use this transaction to set it up right ?

https://github.com/onflow/flow-nft/blob/c13545c37be4d1e63605c5d76340fb188923d997/transactions/setup_account_to_receive_royalty.cdc

@joshuahannan
