### ISSUE TITLE
Create NPM package

### ISSUE THREAD

**Issue by satyamakgec** [onflow/flow-nft#91]
**Context:** 

dApp developers need smart contract access to interact with it, It is hard to keep a copy of the contract and transactions within the frontend codebase and it comes with operation overhead if anything gets changed within the contract or transaction. 

**Solution**
Create an npm package for better interaction with the dApp and easy to maintain.

**Comment by bjartek** [comment]
With the introduction of interaction templates I feel that it would be better to create tolling to make it easier for a dapp to submit their interactions to this initiative. 

I do have code in overflow to create an NPM package though if you are interested in that.
