### ISSUE TITLE
Core Views in NFTView

### ISSUE THREAD

**Issue by austinkline** [onflow/flow-nft#98]
**This is a spin-off ticket originating from #74. Please review its comment history for deeper context about what this ticket is for**

A central theme of discussion many of us have brought up is what views should be "required" to be implemented in order to say that a collection has implemented Flow's metadata standard. While individual collections can define their own views, there is also a central set of what some of us have called "core" views 

## What are core views for?

Core views, when all put together, should give a "complete" picture of an NFT on flow. That is.. marketplaces, wallets, and applications should be able to use the NFTView as a central source to obtain information about an item both to transact with and to display. 

## Current Proposed Core Views
- [Display](https://github.com/onflow/flow-nft/blob/master/contracts/MetadataViews.cdc#L39) - "How do I show this NFT?"
- [ExternalURL](https://github.com/onflow/flow-nft/blob/master/contracts/MetadataViews.cdc#L312) - "Where did this NFT come from/how do I make backlinks to this NFT's project?"
- [Medias](https://github.com/onflow/flow-nft/blob/master/contracts/MetadataViews.cdc#L273) - "What is the full image/animation of this NFT? Are there multiple ways to show it?"
- Traits (In PR at #97) - "What data exists on this NFT? What is its Body, Head, Background, Hometown, etc? How do I show this data?"

## Possible missing pieces
- [NftCollectionData](https://github.com/onflow/flow-nft/blob/master/contracts/MetadataViews.cdc#L323) - "How should I store this NFT?"
- TokenURI - Some collections like TopShot have data that exists off-chain. Ideally we can mark how to obtain that extra data or at least note that what an application has could be incomplete

I'm not sure about NftCollectionData, I've flip-flopped on it a few times. TokenURI I think has its place given that some prominent projects are already split, so we know that we will need to handle that.

If anything else is missing, please chime in! The ideal is that we settle on these core views and then we can create a factory method or some kind of helper on the MetadataStandards contract that builds this for you. Then, a collection can just delegate to the factory for building the NftView and it can be practically for free for collection owners to include.

**Comment by austinkline** [comment]
cc @psiemens @bjartek @bluesign

**Comment by bjartek** [comment]
NFTCollectionView and Editions?

**Comment by austinkline** [comment]
> NFTCollectionView and Editions?

Editions I'm unsure of. Does it belong on the top-level? Or should we instead encourage collection owners to make that into a trait?

**Comment by spacepluk** [comment]
Just a few ideas.  It would be nice if the json in TokenURI follows the same schema used in the views. Then you can use them interchangeably or merge them in case of split data projects.

A timestamp could be useful too, so you can check which metadata set is newer (on-chain vs TokenURI).

**Comment by austinkline** [comment]
> A timestamp could be useful too, so you can check which metadata set is newer (on-chain vs TokenURI).

This sounds like a trait to me, by the way

**Comment by austinkline** [comment]
@spacepluk I'd like to keep this discussion focused on views as opposed to things that up-end the entire standard.  If you'd like, please reach out to me in twitter or discord and let's figure it out there? Happy to discuss and then summarize here instead of lots of back and forth on this ticket. I don't want folks shut out from anything, but at the same time a TokenURI taking the entire view's format would split the standard in two. In my opinion, that isn't what this meant to be, but I'm happy to discuss in-depth as needed to get a better idea

**Comment by austinkline** [comment]
> I would suggest
> 
> Collection Data Collection Display Royalties

Royalties makes sense! 

I think the others do as well, but I feel a little weirder about it for some reason. Wouldn't I already know Collection Data/Display by nature of having the item itself? Does it make more sense for some kind of roll-up Collection view just like we are proposing an NftView?

**Comment by bshahid331** [comment]
The use case that comes to mind is a central registry. What if you want to setup a collection for someone but don't have an actual NFT yet?

**Comment by austinkline** [comment]
Sync'd with @bshahid331 yesterday about the CollectionDisplay need, it looks like we will need that view specifically because of some collections putting all their NFTs into one place while representing them as different collection on their sites. Because of that possibility, an NFT needs to be able to tell you the collection (NOTE: not resource collection) that it belongs to. As in, is this a BALLERZ or a SNEAKERZ nft? How do I show each one?

I am good with adding it, we have a need and there isn't really another option given the tools we have at our disposal right now

**Comment by austinkline** [comment]
@joshuahannan this one as well should be good
